### ISSUE TITLE
点击提交没反应

### ISSUE THREAD

**Issue by 5536086** [zayabighead/msautocreate#1]
根据教程要求注册了一个应用以及新建了密钥，都填进去了，点击提交按钮，闪了一下就结束了，自助注册不成功

**Comment by realByg** [comment]
要我猜是什么错误么。。好歹f12看看返回什么错误截下图

**Comment by tanst** [comment]
https://sdfsf3.gd520.workers.dev/
大佬帮我看看，我也是没反应呢？

**Comment by realByg** [comment]
> https://sdfsf3.gd520.workers.dev/
> 大佬帮我看看，我也是没反应呢？

{"error":{"code":"Authorization_RequestDenied","message":"Insufficient privileges to complete the operation.","innerError":{"request-id":"112dbce6-0c37-4187-b4f2-d7638748ace4","date":"2020-05-06T05:42:21"}}}

你没有给app授权，我的锅，教程里没写全，给app授权microsoft graph 的read write all权限

**Comment by tanst** [comment]
skuid 获取很简单的
在 Microsoft 365 admin center 管理面板-账单-许可证
然后点击你想看的「许可证」，在地址栏就有 skuid 了
